"""
Django settings for dechet_backend project.

Generated by 'django-admin startproject' using Django 4.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

LANGUAGE_CODE = 'fr'

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

from datetime import timedelta
import os

SECRET_KEY = os.environ.get('SECRET_KEY', '!cju7=vlmhp3obe0ku3@t(a+a!oysasx#^&!%o+nk^%r*z0ei%')  

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=30),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': False,
    'UPDATE_LAST_LOGIN': False,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY, 
    'AUDIENCE': None,
    'ISSUER': None,
    'JWK_URL': None,
    'LEEWAY': 0,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'USER_AUTHENTICATION_RULE': 'rest_framework_simplejwt.authentication.default_user_authentication_rule',
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
    'JTI_CLAIM': 'jti',
    'SLIDING_TOKEN_REFRESH_EXP_CLAIM': 'refresh_exp',
    'SLIDING_TOKEN_LIFETIME': timedelta(minutes=5),
    'SLIDING_TOKEN_REFRESH_LIFETIME': timedelta(days=1),
}




# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-%(a5az!lt%4)$2!n!&8_tx3u$4(khbx$(74*4bs==n8n9#7#y&'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False


ALLOWED_HOSTS = ['DOSSOUYOVO1.pythonanywhere.com', '127.0.0.1']

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework_simplejwt',  # Ajoutez cette ligne
    'rest_framework',
    'utilisateurs',
      'corsheaders',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    #'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'dechet_backend.urls'


TEMPLATES = [
    {
        
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'dechet_backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

import os
import sys

# Add your project directory to the sys.path
# This is the ABSOLUTE path to the root folder of your Django project.
# It's now '/home/DOSSOUYOVO1/dechet_backend'
project_home = '/home/DOSSOUYOVO1/dechet_backend'  # <--- Chemin CORRECT !
if project_home not in sys.path:
    sys.path.insert(0, project_home)

# Set environment variable to tell Django where your settings.py is
# This should be the name of the Python folder that contains your settings.py.
# If settings.py is in /home/DOSSOUYOVO1/dechet_backend/dechet_backend/settings.py, use 'dechet_backend.settings'.
# If it's directly in /home/DOSSOUYOVO1/dechet_backend/settings.py, use 'dechet_backend.settings' as well.
os.environ['DJANGO_SETTINGS_MODULE'] = 'dechet_backend.settings'  # <--- Nom CORRECT !

# --- Database Environment Variables ---
os.environ['MYSQL_DATABASE_NAME'] = 'DOSSOUYOVO1$dechet_app_db'
os.environ['MYSQL_DATABASE_USER'] = 'DOSSOUYOVO1'
# IMPORTANT: Replace 'YOUR_MYSQL_PASSWORD' with the ACTUAL password you set for your MySQL database on PythonAnywhere.
os.environ['MYSQL_DATABASE_PASSWORD'] = 'VOTRE_MOT_DE_PASSE_MYSQL'  # <--- METTEZ VOTRE VRAI MOT DE PASSE ICI !
os.environ['MYSQL_DATABASE_HOST'] = 'DOSSOUYOVO1.mysql.pythonanywhere-services.com'
os.environ['MYSQL_DATABASE_PORT'] = '3306'

# --- Django Secret Key Environment Variable (VERY IMPORTANT!) ---
# This is the key you generated: gnvy4ej@(ctgs2%-8rf4p_=6w-%z_-qu0to5(^@ox#t7h@l$cx
os.environ['SECRET_KEY'] = 'gnvy4ej@(ctgs2%-8rf4p_=6w-%z_-qu0to5(^@ox#t7h@l$cx' # <--- VOTRE CLÉ SECRÈTE DE PRODUCTION

# Serve Django via WSGI
from django.core.wsgi import get_wsgi_application
application = get_wsgi_application()

# If you are using Whitenoise to serve static files (recommended in production),
# uncomment the lines below AFTER you have installed and configured it in settings.py
# from whitenoise.django import DjangoWhiteNoise
# application = DjangoWhiteNoise(application)

# 1. Activez la gestion des fuseaux horaires


USE_TZ = True


TIME_ZONE = 'Africa/Porto-Novo' 
LANGUAGE_CODE = 'fr-fr'
USE_I18N = True 
USE_L10N = True 


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',
)

AUTH_USER_MODEL = 'utilisateurs.CustomUser'  

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
}
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Configuration pour l'envoi d'e-mails via Gmail

from decouple import config
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='dossou7117611@gmail.com ')
EMAIL_HOST_PASSWORD=config('EMAIL_HOST_PASSWORD')


import os
from dotenv import load_dotenv

load_dotenv()

# --- Configuration de l'API Kkiapay ---
KKIAPAY_API_BASE_URL = os.environ.get('KKIAPAY_API_BASE_URL','https://api-sandbox.kkiapay.me/api/v1')
KKIAPAY_PUBLIC_KEY = os.environ.get('KKIAPAY_PUBLIC_KEY','6f25ee36979727a9b3d3a602c42de1b0f78c65a4') # Clé publique de test
KKIAPAY_SECRET_KEY = os.environ.get('KKIAPAY_SECRET_KEY','sk_7a2c8cade43107b2bd95a5b58b9edcb18f7bf4ec4207ee2a53f81617721988e7') # Clé secrète de test pour les décaissements
KKIAPAY_MERCHANT_ID = os.environ.get('KKIAPAY_MERCHANT_ID','6830f4003605b0dc57721586')

# pour tester votre application Flutter.
KKIAPAY_TEST_NUMBERS = [
    '97000000', # Pour les succès
    '97000001', # Pour les échecs
]