# Generated by Django 4.2 on 2025-06-05 18:32

from django.conf import settings
import django.contrib.auth.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import utilisateurs.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(blank=True, max_length=150, null=True, validators=[django.core.validators.RegexValidator(message="Le nom d'utilisateur doit contenir uniquement des lettres et des espaces.", regex='^[A-Za-zÀ-ÿ\\s]+$')], verbose_name="Nom d'utilisateur")),
                ('id_formatte', models.CharField(max_length=10, unique=True, verbose_name='ID Formaté')),
                ('email', models.EmailField(max_length=254, verbose_name='Adresse Email')),
                ('adresse', models.CharField(blank=True, max_length=255, null=True, verbose_name='Adresse')),
                ('user_type', models.CharField(choices=[('citoyen', 'Citoyen'), ('admin', 'Administrateur'), ('collector', 'Collecteur')], default='citoyen', max_length=20, verbose_name="Type d'Utilisateur")),
                ('groups', models.ManyToManyField(blank=True, related_name='customuser_set', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='customuser_set', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='SacTri',
            fields=[
                ('idformatter_sac', models.CharField(default=utilisateurs.models.generate_numeric_id, editable=False, max_length=8, primary_key=True, serialize=False, unique=True, verbose_name='ID formatter du sac')),
                ('couleur', models.CharField(choices=[('vert', 'Vert'), ('jaune', 'Jaune'), ('noir', 'Noir')], max_length=10, verbose_name='Couleur du sac')),
                ('statut', models.CharField(choices=[('Disponible', 'Disponible'), ('Utilisé', 'Utilisé')], default='Disponible', max_length=20, verbose_name='Statut du sac')),
            ],
            options={
                'verbose_name': 'Sac',
                'verbose_name_plural': 'Sacs',
            },
        ),
        migrations.CreateModel(
            name='Retrait',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('nom_beneficiaire', models.CharField(max_length=100)),
                ('prenom_beneficiaire', models.CharField(blank=True, max_length=100, null=True)),
                ('numero_beneficiaire', models.CharField(max_length=20, null=True)),
                ('date_demande', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('approuve', 'Approuvé'), ('rejete', 'Rejeté'), ('echec_kkiapay', 'Échec Kkiapay'), ('complete_kkiapay', 'Terminé par Kkiapay')], default='en_attente', max_length=20)),
                ('date_traitement', models.DateTimeField(blank=True, null=True)),
                ('transaction_id_fournisseur', models.CharField(blank=True, max_length=255, null=True)),
                ('message_echec', models.TextField(blank=True, null=True)),
                ('citoyen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='retraits_initie_citoyen', to=settings.AUTH_USER_MODEL)),
                ('collecteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retraits_demandes_collecteur', to=settings.AUTH_USER_MODEL)),
                ('traite_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retraits_traites', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlanificationCollecte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ville', models.CharField(max_length=100)),
                ('quartier', models.CharField(max_length=100)),
                ('date_collecte', models.DateField()),
                ('heure_collecte', models.TimeField()),
                ('collecteurs_assignes', models.ManyToManyField(related_name='planifications_collecte', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Planification de Collecte',
                'verbose_name_plural': 'Planifications de Collecte',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Collecte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_collecte', models.DateTimeField(auto_now_add=True, verbose_name='Date de collecte')),
                ('point_vert', models.IntegerField(default=0, verbose_name='Points sacs verts')),
                ('point_jaune', models.IntegerField(default=0, verbose_name='Points sacs jaunes')),
                ('point_noir', models.IntegerField(default=0, verbose_name='Points sacs noirs')),
                ('total_collectes_collecteur_citoyen', models.IntegerField(default=0, verbose_name='Total des collectes de ce collecteur pour ce citoyen')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('en_cours', 'En cours'), ('en_cours_scan', 'En cours de scan'), ('termine', 'Terminé'), ('annule', 'Annulé')], default='en_attente', max_length=20, verbose_name='Statut de la collecte')),
                ('citoyen', models.ForeignKey(limit_choices_to={'user_type': 'citoyen'}, on_delete=django.db.models.deletion.CASCADE, related_name='collectes_citoyen', to=settings.AUTH_USER_MODEL, verbose_name='Citoyen')),
                ('collecteur', models.ForeignKey(blank=True, limit_choices_to={'user_type': 'collecteur'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collectes_collecteur', to=settings.AUTH_USER_MODEL, verbose_name='Collecteur')),
            ],
            options={
                'verbose_name': 'Collecte',
                'verbose_name_plural': 'Collectes',
                'ordering': ['-date_collecte'],
            },
        ),
        migrations.CreateModel(
            name='SacCitoyen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sac_vert', models.IntegerField(default=0, verbose_name='Nombre de sacs verts')),
                ('sac_noir', models.IntegerField(default=0, verbose_name='Nombre de sacs noirs')),
                ('sac_jaune', models.IntegerField(default=0, verbose_name='Nombre de sacs jaunes')),
                ('adresse', models.CharField(blank=True, max_length=255, null=True, verbose_name='Adresse')),
                ('date_reception', models.DateTimeField(auto_now=True)),
                ('citoyen', models.ForeignKey(limit_choices_to={'user_type': 'citoyen'}, on_delete=django.db.models.deletion.CASCADE, related_name='sacs_recus', to=settings.AUTH_USER_MODEL, verbose_name='Citoyen')),
            ],
            options={
                'verbose_name': 'Sac attribué au citoyen',
                'verbose_name_plural': 'Sacs attribués aux citoyens',
                'unique_together': {('citoyen',)},
            },
        ),
    ]
