# Generated by Django 4.2 on 2025-05-05 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SacTri',
            fields=[
                ('idformatter_sac', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True, verbose_name='ID formatter du sac')),
                ('couleur', models.CharField(choices=[('vert', 'Vert'), ('jaune', 'Jaune'), ('noir', 'Noir')], max_length=10, verbose_name='Couleur du sac')),
                ('statut', models.CharField(choices=[('Disponible', 'Disponible'), ('Utilisé', 'Utilisé')], default='Disponible', max_length=20, verbose_name='Statut du sac')),
            ],
            options={
                'verbose_name': 'Sac',
                'verbose_name_plural': 'Sacs',
            },
        ),
    ]
