# Generated by Django 4.2 on 2025-05-05 15:16

from django.db import migrations, models
import utilisateurs.models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0002_sactri'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sactri',
            name='idformatter_sac',
            field=models.CharField(default=utilisateurs.models.generate_numeric_id, editable=False, max_length=8, primary_key=True, serialize=False, unique=True, verbose_name='ID formatter du sac'),
        ),
    ]
