# Generated by Django 4.2 on 2025-05-06 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0003_alter_sactri_idformatter_sac'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='date_reception_sac',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de réception des sacs'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='sac_jaune',
            field=models.IntegerField(default=0, verbose_name='Nombre de sacs jaunes'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='sac_noir',
            field=models.IntegerField(default=0, verbose_name='Nombre de sacs noirs'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='sac_vert',
            field=models.IntegerField(default=0, verbose_name='Nombre de sacs verts'),
        ),
    ]
