# Generated by Django 4.2 on 2025-05-06 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0004_customuser_date_reception_sac_customuser_sac_jaune_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='date_reception_sac',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='sac_jaune',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='sac_noir',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='sac_vert',
        ),
    ]
