# Generated by Django 4.2 on 2025-05-06 08:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0005_remove_customuser_date_reception_sac_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SacCitoyen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sac_vert', models.IntegerField(default=0, verbose_name='Nombre de sacs verts')),
                ('sac_noir', models.IntegerField(default=0, verbose_name='Nombre de sacs noirs')),
                ('sac_jaune', models.IntegerField(default=0, verbose_name='Nombre de sacs jaunes')),
                ('date_reception', models.DateTimeField(auto_now_add=True, verbose_name="Date d'attribution")),
                ('citoyen', models.ForeignKey(limit_choices_to={'user_type': 'citoyen'}, on_delete=django.db.models.deletion.CASCADE, related_name='sacs_recus', to=settings.AUTH_USER_MODEL, verbose_name='Citoyen')),
            ],
            options={
                'verbose_name': 'Sac attribué au citoyen',
                'verbose_name_plural': 'Sacs attribués aux citoyens',
                'unique_together': {('citoyen',)},
            },
        ),
    ]
