# Generated by Django 4.2 on 2025-05-06 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0006_saccitoyen'),
    ]

    operations = [
        migrations.AddField(
            model_name='saccitoyen',
            name='adresse',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Adresse de réception'),
        ),
    ]
