# Generated by Django 4.2 on 2025-05-07 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0007_saccitoyen_adresse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saccitoyen',
            name='date_reception',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
