# Generated by Django 4.2 on 2025-05-07 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0008_alter_saccitoyen_date_reception'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saccitoyen',
            name='date_reception',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
