# Generated by Django 4.2 on 2025-05-07 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0009_alter_saccitoyen_date_reception'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saccitoyen',
            name='adresse',
            field=models.CharField(blank=True, max_length=255, verbose_name='Adresse de réception'),
        ),
    ]
