# Generated by Django 4.2 on 2025-05-08 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0010_alter_saccitoyen_adresse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saccitoyen',
            name='adresse',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Adresse de réception'),
        ),
    ]
