# Generated by Django 4.2 on 2025-05-11 01:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0012_alter_saccitoyen_adresse'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collecte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_collecte', models.DateTimeField(auto_now_add=True, verbose_name='Date de collecte')),
                ('point_vert', models.IntegerField(default=0, verbose_name='Points sacs verts')),
                ('point_jaune', models.IntegerField(default=0, verbose_name='Points sacs jaunes')),
                ('point_noir', models.IntegerField(default=0, verbose_name='Points sacs noirs')),
                ('citoyen', models.ForeignKey(limit_choices_to={'user_type': 'citoyen'}, on_delete=django.db.models.deletion.CASCADE, related_name='collectes_citoyen', to=settings.AUTH_USER_MODEL, verbose_name='Citoyen')),
                ('collecteur', models.ForeignKey(blank=True, limit_choices_to={'user_type': 'collecteur'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collectes_collecteur', to=settings.AUTH_USER_MODEL, verbose_name='Collecteur')),
            ],
            options={
                'verbose_name': 'Collecte',
                'verbose_name_plural': 'Collectes',
                'ordering': ['-date_collecte'],
            },
        ),
    ]
