# Generated by Django 4.2 on 2025-05-12 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0013_collecte'),
    ]

    operations = [
        migrations.AddField(
            model_name='collecte',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('en_cours', 'En cours'), ('termine', 'Terminé'), ('annule', 'Annulé')], default='en_attente', max_length=20, verbose_name='Statut de la collecte'),
        ),
    ]
