# Generated by Django 4.2 on 2025-05-12 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0014_collecte_statut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collecte',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('en_cours', 'En cours'), ('en_cours_scan', 'En cours de scan'), ('termine', 'Terminé'), ('annule', 'Annulé')], default='en_attente', max_length=20, verbose_name='Statut de la collecte'),
        ),
    ]
