# Generated by Django 4.2 on 2025-05-17 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0015_alter_collecte_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='collecte',
            name='total_collectes_citoyen',
            field=models.IntegerField(default=0, verbose_name='Total des collectes du citoyen'),
        ),
    ]
