# Generated by Django 4.2 on 2025-05-19 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0016_collecte_total_collectes_citoyen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collecte',
            name='total_collectes_citoyen',
        ),
        migrations.AddField(
            model_name='collecte',
            name='total_collectes_collecteur_citoyen',
            field=models.IntegerField(default=0, verbose_name='Total des collectes de ce collecteur pour ce citoyen'),
        ),
    ]
