# Generated by Django 4.2 on 2025-05-21 09:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0017_remove_collecte_total_collectes_citoyen_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanificationCollecte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ville', models.CharField(max_length=100)),
                ('quartier', models.CharField(max_length=100)),
                ('date_collecte', models.DateField()),
                ('heure_collecte', models.TimeField()),
                ('collecteurs_assignes', models.ManyToManyField(related_name='planifications_collecte', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Planification de Collecte',
                'verbose_name_plural': 'Planifications de Collecte',
            },
        ),
    ]
