# Generated by Django 4.2 on 2025-05-24 10:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0020_notification_latitude_notification_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='Retrait',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_beneficiaire', models.CharField(max_length=100, verbose_name='Nom du bénéficiaire')),
                ('numero_mtn_beneficiaire', models.CharField(max_length=20, verbose_name='Numéro MTN du bénéficiaire')),
                ('montant_demande', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant demandé')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('succes', 'Succès'), ('echec', 'Échec')], default='en_attente', max_length=20, verbose_name='Statut du retrait')),
                ('date_demande', models.DateTimeField(auto_now_add=True, verbose_name='Date de la demande')),
                ('date_traitement', models.DateTimeField(blank=True, null=True, verbose_name='Date de traitement')),
                ('transaction_id_mtn', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID Transaction MTN')),
                ('message_echec', models.TextField(blank=True, null=True, verbose_name="Message d'échec")),
                ('collecteur', models.ForeignKey(limit_choices_to={'user_type': 'collecteur'}, on_delete=django.db.models.deletion.CASCADE, related_name='demandes_retrait', to=settings.AUTH_USER_MODEL, verbose_name='Collecteur demandeur')),
                ('traite_par', models.ForeignKey(blank=True, limit_choices_to={'user_type': 'admin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Traité par')),
            ],
            options={
                'verbose_name': 'Demande de Retrait',
                'verbose_name_plural': 'Demandes de Retraits',
                'ordering': ['-date_demande'],
            },
        ),
    ]
