# Generated by Django 4.2 on 2025-05-24 11:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0021_retrait'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='retrait',
            options={},
        ),
        migrations.RemoveField(
            model_name='retrait',
            name='montant_demande',
        ),
        migrations.RemoveField(
            model_name='retrait',
            name='numero_mtn_beneficiaire',
        ),
        migrations.RemoveField(
            model_name='retrait',
            name='transaction_id_mtn',
        ),
        migrations.AddField(
            model_name='retrait',
            name='montant',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='retrait',
            name='numero_beneficiaire',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='retrait',
            name='prenom_beneficiaire',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='retrait',
            name='transaction_id_fournisseur',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='retrait',
            name='collecteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retraits_demandes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='retrait',
            name='date_demande',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='retrait',
            name='date_traitement',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='retrait',
            name='message_echec',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='retrait',
            name='nom_beneficiaire',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='retrait',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('approuve', 'Approuvé'), ('rejete', 'Rejeté')], default='en_attente', max_length=20),
        ),
        migrations.AlterField(
            model_name='retrait',
            name='traite_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retraits_traites', to=settings.AUTH_USER_MODEL),
        ),
    ]
