# Generated by Django 4.2 on 2025-05-25 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0022_alter_retrait_options_remove_retrait_montant_demande_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retrait',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('approuve', 'Approuvé'), ('rejete', 'Rejeté'), ('echec_kkiapay', 'Échec Kkiapay'), ('complete_kkiapay', 'Terminé par Kkiapay')], default='en_attente', max_length=20),
        ),
    ]
