# Generated by Django 4.2 on 2025-05-27 18:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0023_alter_retrait_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='retrait',
            name='citoyen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='retraits_initie_citoyen', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='retrait',
            name='collecteur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retraits_demandes_collecteur', to=settings.AUTH_USER_MODEL),
        ),
    ]
